version: 2
registries:
  jfrog:
    type: docker-registry
    url: jfrog.ais.acquia.io
    username: github_dependabot_token
    password: ${{secrets.JFROG_GITHUB_DEPENDABOT_TOKEN}}
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      composer-dependencies:
        patterns:
          - "*"
    registries:
      - jfrog
  - package-ecosystem: "docker"
    directory: "/.acquia"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    registries:
      - jfrog
